version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.2.0

workflows:
  path_filtering:
    jobs:
      - path-filtering/filter:
          name: "Check updated files"
          mapping: |
            gcp-projects/my-projects/.* gcp_my-projects true .circleci/gcp_my-projects.yml
          base-revision: master
          config-path: .circleci/gcp_my-projects.yml