version: 2.1

executors:
  base-image:
    docker:
      - image: cimg/gcp:2025.01

jobs:
  terraform-auth:
    executor: base-image
    steps:
      - checkout
      - run:
          command: |
            echo "gcloud auth activate-service-account --key-file=GCP_TF_SERVICE_ACCOUNT_KEY"
            gcloud --version
            git --version

workflows:
  version: 2
  terraform-workflow:
    jobs:
      - terraform-auth:
          filters:
            branches:
              only:
                - feature/create-circleci-configuration