version: 2.1

orbs:
  terraform: circleci/terraform@3.6.0

parameters:
  gcp-my-projects:
    type: boolean
    default: false
  gcp-hub-project:
    type: boolean
    default: false

workflows:
  my-projects-infra:
    when: << pipeline.parameters.gcp-my-projects >>
    jobs:
      - terraform/fmt:
        name: "Terraform format"
        checkout: true
        context: terraform
        filters:
          branches:
            only: feature/create-circleci-configuration
      - terraform/validate:
        name: "Terraform validate"
        checkout: true
        context: terraform
        filters:
          branches:
            only: feature/create-circleci-configuration
        requires:
          - terraform/fmt
      - terraform/plan:
        name: "Terraform plan"
        checkout: true
        context: terraform
        persist-workspace: true
        filters:
          branches:
            only: feature/create-circleci-configuration
        requires:
          - terraform/validate
      - terraform/apply:
        name: "Terraform apply"
        attach_workspace: true
        context: terraform
        filters:
          branches:
            only: master
        requires:
          - terraform/plan
  hub-project-infra:
    when: << pipeline.parameters.gcp-hub-project >>
    jobs:
      - terraform/fmt:
        name: "Terraform format"
        checkout: true
        context: terraform
        filters:
          branches:
            only: feature/create-circleci-configuration
      - terraform/validate:
        name: "Terraform validate"
        checkout: true
        context: terraform
        filters:
          branches:
            only: feature/create-circleci-configuration
        requires:
          - terraform/fmt
      - terraform/plan:
        name: "Terraform plan"
        checkout: true
        context: terraform
        persist-workspace: true
        filters:
          branches:
            only: feature/create-circleci-configuration
        requires:
          - terraform/validate
      - terraform/apply:
        name: "Terraform apply"
        attach_workspace: true
        context: terraform
        filters:
          branches:
            only: master
        requires:
          - terraform/plan

# jobs:
#   setup-gcp-credentials:
#     executor: base-image
#     steps:
#       - run:
#           command: |
#             echo "$GCP_TERRAFORM_SERVICE_KEY" > /tmp/gcp-tf-key.json
#       - persist_to_workspace:
#           root: /tmp
#           paths:
#             - gcp-tf-key.json
    